### ISSUE TITLE
Question about theming

### ISSUE THREAD

**Issue by bsr203** [jamesmontemagno/MVVMSourceGenerators#1]
Hello James
Just started learning about WPF and the toolkit. When I run the sample (both framework & net6) there is no theme to it, just white screen with controls. I wonder how you applies themes, unless the source you demonstrated is different. I see some of the style package applies to App.xaml, and son't see it in yours.
Thanks for your wonderful tutorials.
bsr.

**Comment by jamesmontemagno** [comment]
Probably the app I was running was the .NET MAUI app which is fully themed. For WPF I would google around for that and use a framework. I used to use Mahapps.

**Comment by bsr203** [comment]
Thank you for the response.
